### PR TITLE
add container build GH action

### PR DESCRIPTION
**Pull request by tuminoid**
Add container build GH action for ipxe-builder.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
After https://gerrit.nordix.org/c/infra/cicd/+/20394 is merged, we can take this.

**Comment by tuminoid** [comment]
Merged.

/unhold

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
OK, this workflow is the last one. All of the containers are now built with action+Jenkins and Quay builds are disabled. :tada:

**Pull request merged**
