### PR TITLE
redefine the purpose of the repository

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
 - modifies the README

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
> /retest

That is not going to help unfortunately. There is no hack dir nor markdownlint.sh in the repo, hence it cannot work. Make an another PR that adds markdownlint.sh and shellcheck.sh in hack.

**Pull request merged**
