### PR TITLE
🌱 Update container images building workflows and add FakeIPA image building

### PR DESCRIPTION
**Pull request by mboukhalfa**
Fixes: #15

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/hold
We need to make sure that secrets are configured on the repo
@kashifest

**Comment by mboukhalfa** [comment]
/hold cancel

Secrets checked

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by mboukhalfa** [comment]
/assign @Rozzii 

@kashifest can you lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Rozzii — COMMENTED** [review]
/approve

**Pull request merged**
